name: ibcs

channels:
  - conda-forge
  - openeye

dependencies:
  - python >= 3.11
  - numpy
  - pandas
  - qcportal
  - rdkit
  - openeye-toolkits
  - scikit-learn

  # Dev
  - pre-commit
  - loguru
  - ruff
  - mypy
